export const dummyExpenses = [
  {
    id: "EXP001",
    employeeName: "Rahul Sharma",
    employeeId: "EMP101",
    amount: 2450,
    invoiceUrl: "https://morth.nic.in/sites/default/files/dd12-13_0.pdf",
    category: "Travel",
    description: "Client meeting travel expenses",
    submittedDate: "2025-02-10",
    status: "PENDING",
  },
  {
    id: "EXP002",
    employeeName: "Priya Verma",
    employeeId: "EMP102",
    amount: 1800,
    invoiceUrl: "https://example.com/invoices/invoice2.pdf",
    category: "Food",
    description: "Team lunch reimbursement",
    submittedDate: "2025-02-11",
    status: "APPROVED",
  },
  {
    id: "EXP003",
    employeeName: "Amit Patel",
    employeeId: "EMP103",
    amount: 5200,
    invoiceUrl: "https://example.com/invoices/invoice3.pdf",
    category: "Hotel",
    description: "Hotel stay during onsite visit",
    submittedDate: "2025-02-12",
    status: "REJECTED",
  },
  {
    id: "EXP004",
    employeeName: "Neha Singh",
    employeeId: "EMP104",
    amount: 950,
    invoiceUrl: "https://example.com/invoices/invoice4.pdf",
    category: "Office Supplies",
    description: "Stationery purchase",
    submittedDate: "2025-02-13",
    status: "PENDING",
  },
];
